### ISSUE TITLE
如何经过跳板机服务器访问另一个服务器呢？

### ISSUE THREAD

**Issue by Zhu-haow** [silverbulletmdc/showdata#1]
http://<服务器ip>:8000/index.html
这个服务器ip如何经过一个跳板机服务呢？或者服务器在访问时候如何登入账号密码呢

**Comment by silverbulletmdc** [comment]
经过一个跳板机的话可以通过端口转发来讲远程服务器的8000端口映射到本地。
```
ssh -CNL 8000:localhost:8000 <user>@<ip> -p <port>
```
然后本地访问 http://localhost:8000/index.html 即可。
